Kiri11/solutions
kiri11/scala-school pull request #2
Opened 2017-03-12 11:29 UTC by kiri11

## Часть 1. Типы. Задания
Исправить компиляцию
**lectures.types.FixCompile**

## Часть 1. Функции. Задания
Дана заготовка наивной реализации подсчета чисел Фибоначи. Необходимо исправить код
и вывести 9-ое число Фибоначи
**lectures.functions.Fibonacci**
Реализовать более эффективный способ вычисления чисел Фибоначчи
**lectures.functions.Fibonacci2**
Освоить каррирование и функции высшего порядка
**lectures.functions.Computation, lectures.functions.CurriedComputation,
lectures.functions.FunctionalComputation**
Воспользоваться композицией функций для написания простого DB API
**lectures.functions.SQLAPI**

2017-03-13 12:39 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Computations.scala
> +    dataProducer.filter(dataItem => filterData.split(" ").contains(dataItem))
Верни пожалуйста thread.sleep во все имплементации, они нам понадобятся

2017-03-13 12:39 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +  private def logParameter[T](prm: T): T  = {println(prm); prm}
Лучше не делать oneliner с несколькими выражениям.

2017-03-13 12:39 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +  val executor: (String) => String = openConnection(connection) compose logParameter
Попробуй добиться того же эффекта не меняя connection и executor, только за счет их композиции в функции execute.

2017-03-19 22:07 UTC, vatt2001 requested changes

2017-03-19 22:07 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +      Computation.computation(filterData, dataProducer)
Здесь можно оптимизировать, а именно - воспользоваться тем, что возвращаемая функция не зависит от переданного `filterData`

2017-03-26 17:10 UTC, kiri11 commented
@vatt2001 
Результаты оптимизации:
```
Elapsed time in computation(): 11293
Elapsed time in partiallyAppliedCurriedFunction(): 11038
Elapsed time in filterApplied():10031
Difference is about 1007 milliseconds
```

2017-03-27 21:30 UTC, vatt2001 approved these changes

2017-03-27 21:30 UTC, merged